spring:
  application:
    name: customer
  h2:
    console:
      settings:
        trace: true
server:
  port: 6161
  
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true